# -*- coding: utf-8 -*-
"""Radiação_Solar_Alegre_2010-2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p0aXXDj4fLeo9NDj8O-dv8Tzp__baJhj
"""

import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt

radiacao = pd.read_csv('/content/drive/MyDrive/UFES/Estação-Alegre-a617_2010-a-2020_Radiação_4.csv')

#radiacao.head()

radiacao['Data']=pd.to_datetime(radiacao['Data'])
radiacao = radiacao.set_index('Data')
#radiacao.head()

"""Abaixo, em "radiacao = radiacao.resample('D').sum()" é feito o somatório dos dados horários para uma representação diária."""

radiacao = radiacao.resample('D').sum()
radiacao = radiacao.dropna()

"""Plotagem do gráfico concatenado anual da série temporal Estação-Alegre-a617_2010-a-2020_Radiação dos dados horários agrupados por dia."""

radiacao.plot(figsize=(18,8))
plt.xlabel('Meses')
plt.ylabel('índice de Radiação ($KJ/m^2$)')
plt.savefig("Estação-Alegre-a617_2010--2020_Radiação_Solar_300-DPI.png",dpi=300)

"""Plotagem do gráfico separado por ano da série temporal Estação-Alegre-a617_2010-a-2020_Radiação dos dados horários agrupados por dia."""

radiacao.plot(subplots=True, figsize=(12, 15))
plt.xlabel('Meses', fontsize= 12)
plt.ylabel('índice de Radiação ($KJ/m^2$)', fontsize= 12)
plt.savefig("Estação-Alegre-a617_2010--2020_Radiação_Solar_300-DPI_subplot.png",dpi=300)



